name: Jepsen tests

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: jepsen
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: make jepsen

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: tests/logs
